### ISSUE TITLE
Ebean ignores deleted flag when using @OneToOne and find method

### ISSUE THREAD

**Issue by eikigithub** [ebean-orm/examples#10]
Hi, Rob.

The content I sent to the mailing list the other day was classified as spam.
Sorry for the same content, but I will post it as an issue.

I have been using Ebean and noticed that there are cases where the deleted flag is not being considered.
In our project, we utilize the Query#findCount method,
and it appears that the deleted flag may not be taken into account depending on how the entities are related to each other.

To provide more context, I've created some test code in my GitHub repository at https://github.com/eikigithub/examples/compare/master...mytest to demonstrate the issue.

The issue occurred in the following environment:
(I have updated the development environment since I sent the email)
* Windows 11
* Ebean 13.11.0 (The latest version, 13.22.0, also reproduces the problem.)
* Eclipse 2023-09
And my test project setting is:
* pom.xml
** tiles-maven-plugin 2.33 -> 2.35
* application-test.yml
** useDocker: false...enabled

Thanks,
Eiki

**Comment by rob-bygrave** [comment]
Looking at `SqlTreeNodeExtraJoin` there is:

```java
      if (!oneToOneExported && assocBeanProperty.isTargetSoftDelete() && temporalMode != SpiQuery.TemporalMode.SOFT_DELETED) {
        ctx.append(" and ").append(assocBeanProperty.softDeletePredicate(ctx.tableAlias(prefix)));
      }
```
... and the difference between company and invoice is the `oneToOneExported ` value.

NB: git -> show history for selection ... shows us the history with https://github.com/ebean-orm/ebean/issues/2238 bringing in the change adding the `!oneToOneExported && `

**Comment by rob-bygrave** [comment]
The fix in this commit isn't really correct - https://github.com/ebean-orm/ebean/commit/6697aecd48e95fd461d2c97fc29f8455c325149a

... this change fixed that test but introduced this issue (didn't really fix the issue correctly).

**Comment by rbygrave** [comment]
Logged as https://github.com/ebean-orm/ebean/pull/3240

**Comment by eikigithub** [comment]
It's working as expected in our project.
Thanks for fixing it!
I'll close the issue.
