### ISSUE TITLE
Cannot resolve io.ebean:ebean-test-docker:4.0

### ISSUE THREAD

**Issue by waerly** [ebean-orm/examples#4]
help

**Comment by rbygrave** [comment]
https://repo1.maven.org/maven2/io/ebean/ebean-test-docker/4.0/
https://search.maven.org/artifact/io.ebean/ebean-test-docker/4.0/jar

It is in central?  Can you see it in the above links?

**Comment by waerly** [comment]
> https://repo1.maven.org/maven2/io/ebean/ebean-test-docker/4.0/
> https://search.maven.org/artifact/io.ebean/ebean-test-docker/4.0/jar
> 
> It is in central? Can you see it in the above links?

I can see it, but I can’t download it in maven. It may be because I am in China, but thank you
